plugins:
  - "@typescript-eslint"

parser: "@typescript-eslint/parser"

parserOptions:
  project: tsconfig.json
  tsconfigRootDir: .

env:
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking