env:
  node: true
  es6: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  sourceType: module
rules:
  indent: 
    - error
    - 4
  linebreak-style: 
    - error
    - windows
  quotes: 
    - error
    - double
  semi:
    - error
    - always
  prefer-const:
    - error
  no-param-reassign:
    - error
  rest-spread-spacing:
    - error
    - never
  object-curly-spacing: 
    - error
    - always
  comma-spacing:
    - error
  prefer-destructuring:
    - error
  prefer-spread:
    - error
  prefer-rest-params:
    - error
  array-bracket-spacing:
    - error
    - always
  space-infix-ops:
    - error
  space-before-blocks:
    - error
    - always
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true 
  curly:
    - error
    - all
  arrow-spacing:
    - error
  block-spacing:
    - error
    - always
  key-spacing:
    - error
  computed-property-spacing:
    - error
    - never
  no-lone-blocks:
    - error
  no-lonely-if:
    - error
  no-var:
    - error
  max-len:
    - warn
    - code: 80